import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getDictionary,isLocale } from "@/lib/i18n";
export const metadata:Metadata={title:"Metodología",description:"Cómo se calcula la puntuación y la confianza de Bravómetro."};
export default async function Methodology({params}:{params:Promise<{locale:string}>}){
  const{locale}=await params;if(!isLocale(locale))notFound();const d=getDictionary(locale);
  const weights:Array<[string,number]>=[[d.attributes.sauce,24],[d.attributes.potato,20],[d.attributes.taste,20],[d.attributes.spiciness,10],[d.attributes.texture,10],[d.attributes.value,9],[d.attributes.quantity,7]];
  return <><section className="section"><div className="shell"><span className="eyebrow">{d.methodology.eyebrow}</span><h1 className="section-title">{d.methodology.title}</h1><p className="lede">{d.methodology.description}</p><div className="method-grid" style={{marginTop:34}}><article className="card method-card"><span className="method-number">1</span><h2>{d.methodology.formula}</h2><p>{locale==="es"?"La nota global es una media ponderada de siete atributos, redondeada a una decimal. No sustituye el contexto: siempre se muestra junto a la confianza.":"The overall score is a weighted average of seven attributes, rounded to one decimal. Context remains visible through confidence."}</p></article><article className="card method-card"><span className="method-number">2</span><h2>{d.methodology.confidence}</h2><p>{locale==="es"?"La confianza combina volumen de evidencia y diversidad de fuentes. Una nota con poca evidencia nunca se presenta como definitiva.":"Confidence combines evidence volume and source diversity. A score with little evidence is never shown as definitive."}</p></article><article className="card method-card"><span className="method-number">3</span><h2>{d.methodology.sources}</h2><p>{locale==="es"?"Guardamos identificadores, permisos, datos derivados y fechas por separado. No asumimos que una reseña externa puede copiarse indefinidamente.":"We store identifiers, permissions, derived data and dates separately. External reviews are never assumed safe to copy forever."}</p></article></div></div></section><section className="section" style={{background:"#fff3d5"}}><div className="shell"><h2 className="section-title" style={{fontSize:"clamp(2rem,4vw,3rem)"}}>{d.methodology.weights}</h2><div className="card content-card weight-list">{weights.map(([label,value])=><div className="weight-row" key={label}><b>{label}</b><div className="track"><div className="fill" style={{width:`${value*4}%`}}/></div><strong>{value}%</strong></div>)}</div></div></section></>;
}
