import type { Place } from "@/lib/types";

export const demoPlaces: Place[] = [
  {
    id: "sample-casa-salsa",
    name: "Casa Salsa",
    slug: "casa-salsa-demo",
    city: "Madrid",
    country: "ES",
    neighborhood: "Chamberí",
    address: "Dirección de demostración · Madrid",
    latitude: 40.433,
    longitude: -3.704,
    priceLevel: 2,
    status: "demo",
    productType: "bravas",
    scores: { overall: 8.7, potato: 9.1, sauce: 8.8, spiciness: 7.2, taste: 8.9, texture: 9.0, quantity: 8.0, value: 8.4 },
    confidence: "high",
    confidenceScore: 84,
    evidenceCount: 48,
    summary: { es: "Perfil de demostración: destaca una patata crujiente y una salsa intensa. El picante aparece como el atributo más variable.", en: "Demo profile: crisp potatoes and an intense sauce stand out. Heat is the most variable attribute." },
    highlights: { es: ["Patata muy consistente", "Salsa con personalidad", "Picante moderado"], en: ["Consistent potato", "Distinctive sauce", "Moderate heat"] },
    methodologyVersion: "1.0",
    analyzedAt: "2026-09-20",
  },
  {
    id: "sample-la-esquina",
    name: "La Esquina Brava",
    slug: "la-esquina-brava-demo",
    city: "Madrid",
    country: "ES",
    neighborhood: "Lavapiés",
    address: "Dirección de demostración · Madrid",
    latitude: 40.409,
    longitude: -3.702,
    priceLevel: 1,
    status: "demo",
    productType: "bravas",
    scores: { overall: 8.3, potato: 8.0, sauce: 9.2, spiciness: 8.6, taste: 8.7, texture: 7.8, quantity: 8.5, value: 9.0 },
    confidence: "medium",
    confidenceScore: 67,
    evidenceCount: 26,
    summary: { es: "Perfil de demostración: una salsa potente lidera el conjunto, con buena relación calidad/precio y ración generosa.", en: "Demo profile: a bold sauce leads the experience, with strong value and a generous serving." },
    highlights: { es: ["Salsa protagonista", "Picante alegre", "Muy buena relación calidad/precio"], en: ["Sauce-forward", "Lively heat", "Strong value"] },
    methodologyVersion: "1.0",
    analyzedAt: "2026-09-18",
  },
  {
    id: "sample-el-delantal",
    name: "El Delantal",
    slug: "el-delantal-demo",
    city: "Madrid",
    country: "ES",
    neighborhood: "Malasaña",
    address: "Dirección de demostración · Madrid",
    latitude: 40.425,
    longitude: -3.707,
    priceLevel: 3,
    status: "demo",
    productType: "bravas",
    scores: { overall: 7.9, potato: 8.8, sauce: 7.5, spiciness: 6.4, taste: 8.1, texture: 8.6, quantity: 7.2, value: 7.1 },
    confidence: "medium",
    confidenceScore: 54,
    evidenceCount: 17,
    summary: { es: "Perfil de demostración: sobresalen la textura y el punto de la patata; la salsa es más suave y contenida.", en: "Demo profile: texture and potato cooking stand out; the sauce is milder and restrained." },
    highlights: { es: ["Textura crujiente", "Salsa suave", "Presentación cuidada"], en: ["Crisp texture", "Mild sauce", "Careful presentation"] },
    methodologyVersion: "1.0",
    analyzedAt: "2026-09-11",
  },
];
