import type { Locale } from "@/lib/types";

export const locales: Locale[] = ["es", "en"];
export const defaultLocale: Locale = "es";

const dictionaries = {
  es: {
    nav: { home: "Inicio", ranking: "Ranking", places: "Bravas", map: "Mapa", methodology: "Método", meters: "Otros metros", contribute: "Publicar", myRatings: "Mis valoraciones" },
    actions: { explore: "Explorar las mejores", viewRanking: "Ver ranking", viewPlace: "Ver ficha", search: "Buscar", clear: "Limpiar filtros", nearMe: "Bravas cerca de mí", back: "Volver" },
    hero: { eyebrow: "La brújula de la salsa brava", title: "Descubre las mejores bravas.", accent: "Opiniones convertidas en datos.", description: "Busca un sitio, entiende sus bravas y encuentra tu próxima salsa brava con una puntuación que sí explica el porqué.", search: "Busca por bar, barrio o ciudad…", popular: "Ahora mismo, Madrid está en el punto de mira." },
    common: { score: "Puntuación", confidence: "Confianza", evidence: "menciones analizadas", demo: "Datos de demostración", high: "Alta", medium: "Media", low: "Inicial", city: "Ciudad", neighborhood: "Barrio", price: "Precio", all: "Todos", noResults: "No hay coincidencias con esos filtros.", notRated: "Aún no valorado", loading: "Preparando la salsa…", sampleNotice: "Estos datos son de demostración y no representan valoraciones reales." },
    ranking: { eyebrow: "Clasificación Bravómetro", title: "El ranking con más salsa", description: "Compara puntuación, confianza y atributos. Los datos demo sirven para validar el producto; no son críticas reales.", sortScore: "Mejor puntuación", sortConfidence: "Mayor confianza", sortEvidence: "Más evidencias" },
    places: { eyebrow: "Guía de bravas", title: "Tu próxima parada", description: "Explora establecimientos, compara perfiles y decide según la patata, la salsa o el picante.", results: "establecimientos" },
    detail: { overview: "El perfil de estas bravas", breakdown: "Desglose", summary: "Lo que cuentan los datos", highlights: "Claves del análisis", evidenceTitle: "Evidencias", evidencePending: "Los fragmentos de fuentes se mostrarán aquí cuando exista permiso para almacenarlos y atribuirlos.", communityPhotos: "Fotos de la comunidad", analyzed: "Analizado", methodology: "Metodología", address: "Dónde encontrarlas", visitSite: "Visitar web" },
    attributes: { potato: "Patata", sauce: "Salsa", spiciness: "Picante", taste: "Sabor", texture: "Textura", quantity: "Cantidad", value: "Calidad/precio" },
    methodology: { eyebrow: "Transparencia", title: "Aquí no puntuamos a ojo", description: "Bravómetro transforma señales de distintas fuentes en atributos comparables. Cada resultado conserva su versión metodológica, volumen de evidencia y nivel de confianza.", formula: "La fórmula inicial", confidence: "Cómo medimos la confianza", sources: "Fuentes, con trazabilidad", weights: "Pesos de la versión 1.0" },
    map: { eyebrow: "Sobre el terreno", title: "Madrid, a golpe de salsa", description: "Explora el mapa sin compartir tu ubicación. Solo la pediremos si eliges buscar cerca de ti.", locationReady: "Ubicación aproximada activada", locationError: "No pudimos obtener tu ubicación. El mapa sigue funcionando." },
    meters: { eyebrow: "El laboratorio gastronómico", title: "Más metros gastronómicos", description: "Hoy medimos bravas. Mañana, quién sabe hasta dónde llega la salsa.", kitchen: "En la cocina…", unavailable: "Este medidor es una idea en preparación. Aún no tiene ranking ni datos publicados.", primary: "Bravómetro sigue siendo nuestro producto principal." },
    admin: { eyebrow: "Gestión", title: "Mesa de control", description: "Crea establecimientos y valoraciones en Convex. Las operaciones requieren el token de administración del servidor.", setup: "Para activar la administración configura Convex y BRAVOMETRO_ADMIN_TOKEN.", token: "Token de administración", name: "Nombre", slug: "Slug", save: "Guardar establecimiento", rating: "Valoración", delete: "Eliminar", protected: "Área protegida" },
    contribute: { eyebrow: "Comunidad", title: "Encuentra, comprueba y valora", description: "Busca el sitio o descubre qué tienes cerca, comprueba su ubicación en el mapa y valora sus bravas en un solo paso.", signIn: "Iniciar sesión para valorar", findPlace: "¿Dónde están esas bravas?", ratePlace: "Valora sus bravas", searchLabel: "Busca el establecimiento en Google", searchPlaceholder: "Nombre del bar y ciudad…", searchHelp: "Elige el resultado correcto en la lista o en el mapa. Si aún no existe en Bravómetro, lo añadiremos automáticamente al enviar tu valoración.", submitRating: "Enviar valoración", ratingPending: "Valoración enviada. Queda pendiente de moderación.", pending: "Tu valoración se ha guardado y está pendiente de revisión.", setup: "Las valoraciones se activarán al configurar Clerk, Google Places y Convex.", comment: "Comentario opcional", photo: "Foto de las bravas", photoHelp: "Opcional. La optimizamos antes de subirla y no será pública hasta aprobar la valoración.", addPhoto: "Añadir una foto", removePhoto: "Quitar foto", photoPreview: "Vista previa de la foto", processingPhoto: "Procesando la foto…", uploadingPhoto: "Subiendo la foto…", photoError: "No se pudo subir la foto", photoFormats: "JPG, PNG, WebP, HEIC o HEIF · máximo 15 MB", communityScore: "Valoración de la comunidad", moderated: "El establecimiento se verifica con Google y se añade automáticamente si hace falta; las valoraciones se moderan antes de incorporarse.", nearMe: "Cerca de mí", locating: "Localizando…", locationReady: "Tu ubicación solo se usa para ordenar los sitios cercanos y no se guarda.", locationError: "No hemos podido obtener tu ubicación. Revisa el permiso del navegador.", locationUnsupported: "Este navegador no permite obtener tu ubicación.", mapSetup: "El mapa se activará al configurar la clave pública de Google Maps.", selectPlace: "Selecciona un sitio", selectPlaceHelp: "Pulsa un resultado o un marcador para confirmar dónde estás valorando.", noPlaces: "No hemos encontrado establecimientos con esa búsqueda.", results: "resultados" },
    account: { eyebrow: "Tu cuenta", title: "Mis valoraciones", description: "Consulta todas las bravas que has valorado y el estado de cada publicación.", emptyTitle: "Todavía no has valorado ninguna brava", emptyDescription: "Encuentra un establecimiento y estrena tu historial.", signInTitle: "Inicia sesión para ver tus valoraciones", signInDescription: "Tu historial es privado y solo se muestra con tu cuenta.", rateNow: "Valorar unas bravas", edit: "Actualizar valoración", pending: "Pendiente", approved: "Publicada", rejected: "No publicada", originalDate: "Enviada", updatedDate: "Actualizada" },
    footer: { tagline: "Opiniones convertidas en información que puedes saborear.", legal: "Producto independiente. Las marcas y fuentes externas pertenecen a sus titulares.", discover: "Descubre otros metros" },
  },
  en: {
    nav: { home: "Home", ranking: "Ranking", places: "Bravas", map: "Map", methodology: "Method", meters: "Other meters", contribute: "Post", myRatings: "My ratings" },
    actions: { explore: "Explore the best", viewRanking: "View ranking", viewPlace: "View profile", search: "Search", clear: "Clear filters", nearMe: "Bravas near me", back: "Back" },
    hero: { eyebrow: "Your salsa brava compass", title: "Find the best patatas bravas.", accent: "Opinions turned into data.", description: "Search a place, understand its bravas and find your next salsa brava through a score that explains why.", search: "Search by bar, area or city…", popular: "Right now, Madrid is in the spotlight." },
    common: { score: "Score", confidence: "Confidence", evidence: "mentions analyzed", demo: "Demo data", high: "High", medium: "Medium", low: "Early", city: "City", neighborhood: "Area", price: "Price", all: "All", noResults: "No matches for those filters.", notRated: "Not rated yet", loading: "Preparing the salsa…", sampleNotice: "This is demonstration data and does not represent real reviews." },
    ranking: { eyebrow: "Bravómetro chart", title: "The ranking with extra sauce", description: "Compare score, confidence and attributes. Demo data validates the product and is not a real critique.", sortScore: "Best score", sortConfidence: "Highest confidence", sortEvidence: "Most evidence" },
    places: { eyebrow: "Bravas guide", title: "Your next stop", description: "Explore venues, compare profiles and choose by potato, sauce or heat.", results: "places" },
    detail: { overview: "The profile of these bravas", breakdown: "Breakdown", summary: "What the data says", highlights: "Analysis highlights", evidenceTitle: "Evidence", evidencePending: "Source excerpts will appear here when we have permission to store and attribute them.", communityPhotos: "Community photos", analyzed: "Analyzed", methodology: "Methodology", address: "Where to find them", visitSite: "Visit website" },
    attributes: { potato: "Potato", sauce: "Sauce", spiciness: "Heat", taste: "Taste", texture: "Texture", quantity: "Quantity", value: "Value" },
    methodology: { eyebrow: "Transparency", title: "No guesswork in this score", description: "Bravómetro turns signals from different sources into comparable attributes. Every result keeps its methodology version, evidence volume and confidence level.", formula: "The initial formula", confidence: "How confidence works", sources: "Traceable sources", weights: "Version 1.0 weights" },
    map: { eyebrow: "On the ground", title: "Madrid, one sauce at a time", description: "Explore without sharing your location. We only ask when you choose nearby search.", locationReady: "Approximate location enabled", locationError: "We could not get your location. The map still works." },
    meters: { eyebrow: "The food lab", title: "More food meters", description: "Today we measure bravas. Tomorrow, who knows how far the sauce will go.", kitchen: "In the kitchen…", unavailable: "This meter is still being prepared. It has no ranking or published data yet.", primary: "Bravómetro remains our main product." },
    admin: { eyebrow: "Management", title: "Control table", description: "Create places and ratings in Convex. Operations require the server administration token.", setup: "Configure Convex and BRAVOMETRO_ADMIN_TOKEN to enable administration.", token: "Admin token", name: "Name", slug: "Slug", save: "Save place", rating: "Rating", delete: "Delete", protected: "Protected area" },
    contribute: { eyebrow: "Community", title: "Find, check and rate", description: "Search for the venue or discover what is nearby, confirm it on the map and rate its bravas in one step.", signIn: "Sign in to rate", findPlace: "Where are those bravas?", ratePlace: "Rate their bravas", searchLabel: "Find the venue on Google", searchPlaceholder: "Venue name and city…", searchHelp: "Choose the correct result in the list or on the map. If it is not in Bravómetro yet, we add it automatically when you submit your rating.", submitRating: "Send rating", ratingPending: "Rating submitted. It is awaiting moderation.", pending: "Your rating was saved and is awaiting review.", setup: "Ratings will activate after Clerk, Google Places and Convex are configured.", comment: "Optional comment", photo: "Photo of the bravas", photoHelp: "Optional. We optimize it before upload and it stays private until the rating is approved.", addPhoto: "Add a photo", removePhoto: "Remove photo", photoPreview: "Photo preview", processingPhoto: "Processing photo…", uploadingPhoto: "Uploading photo…", photoError: "The photo could not be uploaded", photoFormats: "JPG, PNG, WebP, HEIC or HEIF · 15 MB maximum", communityScore: "Community rating", moderated: "The venue is verified with Google and added automatically if needed; ratings are moderated before being included.", nearMe: "Near me", locating: "Locating…", locationReady: "Your location is only used to sort nearby venues and is not stored.", locationError: "We could not get your location. Check your browser permission.", locationUnsupported: "This browser cannot provide your location.", mapSetup: "The map will activate after configuring the public Google Maps key.", selectPlace: "Select a venue", selectPlaceHelp: "Tap a result or marker to confirm where you are rating.", noPlaces: "We could not find any venues for that search.", results: "results" },
    account: { eyebrow: "Your account", title: "My ratings", description: "See every plate of bravas you have rated and each publication status.", emptyTitle: "You have not rated any bravas yet", emptyDescription: "Find a venue and start your history.", signInTitle: "Sign in to see your ratings", signInDescription: "Your history is private and only shown with your account.", rateNow: "Rate some bravas", edit: "Update rating", pending: "Pending", approved: "Published", rejected: "Not published", originalDate: "Sent", updatedDate: "Updated" },
    footer: { tagline: "Opinions turned into information you can taste.", legal: "Independent product. External brands and sources belong to their owners.", discover: "Discover other meters" },
  },
} as const;

export type Dictionary = (typeof dictionaries)["es"];

export function isLocale(value: string): value is Locale {
  return locales.includes(value as Locale);
}

export function getDictionary(locale: Locale): Dictionary {
  return dictionaries[locale] as Dictionary;
}
