import { mutation,query } from "./_generated/server";
import { v } from "convex/values";
import { overallFromRating, overallFromScores } from "./ratingMath";

function authorize(token:string){if(!process.env.BRAVOMETRO_ADMIN_TOKEN||token!==process.env.BRAVOMETRO_ADMIN_TOKEN)throw new Error("Unauthorized")}
function confidence(evidence:number){return Math.round(Math.min(evidence/40,1)*75+25/3)}
const scores=v.object({potato:v.number(),sauce:v.number(),spiciness:v.number(),taste:v.number(),texture:v.number(),quantity:v.number(),value:v.number()});

export const upsertPlace=mutation({args:{adminToken:v.string(),name:v.string(),slug:v.string(),city:v.string(),country:v.string(),neighborhood:v.string(),address:v.string()},handler:async(ctx,args)=>{authorize(args.adminToken);const existing=await ctx.db.query("places").withIndex("by_slug",q=>q.eq("slug",args.slug)).unique();const data={name:args.name,slug:args.slug,city:args.city,country:args.country,neighborhood:args.neighborhood,address:args.address,priceLevel:2,status:"published" as const,updatedAt:Date.now()};if(existing){await ctx.db.patch(existing._id,data);return existing._id}return ctx.db.insert("places",{...data,source:"admin",createdAt:Date.now()})}});
export const upsertRating=mutation({args:{adminToken:v.string(),placeSlug:v.string(),scores,evidenceCount:v.number(),summaryEs:v.string(),summaryEn:v.string()},handler:async(ctx,args)=>{authorize(args.adminToken);const place=await ctx.db.query("places").withIndex("by_slug",q=>q.eq("slug",args.placeSlug)).unique();if(!place)throw new Error("Place not found");const existing=await ctx.db.query("dishRatings").withIndex("by_place",q=>q.eq("placeId",place._id)).filter(q=>q.eq(q.field("productType"),"bravas")).first();const data={placeId:place._id,productType:"bravas" as const,dishType:"patatas-bravas",overallScore:overallFromScores(args.scores),potatoScore:args.scores.potato,sauceScore:args.scores.sauce,spicinessScore:args.scores.spiciness,tasteScore:args.scores.taste,textureScore:args.scores.texture,quantityScore:args.scores.quantity,valueScore:args.scores.value,confidenceScore:confidence(args.evidenceCount),evidenceCount:args.evidenceCount,summaryEs:args.summaryEs,summaryEn:args.summaryEn,highlightsEs:[],highlightsEn:[],analyzedAt:Date.now(),methodologyVersion:"1.0",updatedAt:Date.now()};if(existing){await ctx.db.patch(existing._id,data);return existing._id}return ctx.db.insert("dishRatings",{...data,createdAt:Date.now()})}});
export const deletePlace=mutation({args:{adminToken:v.string(),placeId:v.id("places")},handler:async(ctx,args)=>{authorize(args.adminToken);const ratings=await ctx.db.query("dishRatings").withIndex("by_place",q=>q.eq("placeId",args.placeId)).collect();for(const rating of ratings)await ctx.db.delete(rating._id);const evidence=await ctx.db.query("reviewEvidence").withIndex("by_place",q=>q.eq("placeId",args.placeId)).collect();for(const row of evidence)await ctx.db.delete(row._id);await ctx.db.delete(args.placeId)}});
export const deleteRating=mutation({args:{adminToken:v.string(),placeSlug:v.string()},handler:async(ctx,args)=>{authorize(args.adminToken);const place=await ctx.db.query("places").withIndex("by_slug",q=>q.eq("slug",args.placeSlug)).unique();if(!place)throw new Error("Place not found");const ratings=await ctx.db.query("dishRatings").withIndex("by_place",q=>q.eq("placeId",place._id)).collect();for(const rating of ratings)if(rating.productType==="bravas")await ctx.db.delete(rating._id)}});
export const listPending=query({args:{adminToken:v.string()},handler:async(ctx,args)=>{authorize(args.adminToken);const places=await ctx.db.query("placeSubmissions").withIndex("by_status",q=>q.eq("status","pending")).order("desc").take(100);const pendingRatings=await ctx.db.query("userRatings").withIndex("by_status",q=>q.eq("status","pending")).order("desc").take(100);const ratings=[];for(const rating of pendingRatings){const place=await ctx.db.get(rating.placeId);ratings.push({...rating,placeName:place?.name??"Sitio eliminado",photoUrl:rating.photoStorageId?await ctx.storage.getUrl(rating.photoStorageId):undefined})}return{places,ratings}}});
export const approvePlaceSubmission=mutation({args:{adminToken:v.string(),submissionId:v.id("placeSubmissions"),slug:v.string(),city:v.string(),country:v.string(),neighborhood:v.string()},handler:async(ctx,args)=>{authorize(args.adminToken);const submission=await ctx.db.get(args.submissionId);if(!submission||submission.status!=="pending")throw new Error("Submission not found");const duplicate=await ctx.db.query("places").withIndex("by_external_place",q=>q.eq("externalPlaceId",submission.googlePlaceId)).first();if(duplicate)throw new Error("Place already exists");const slugExists=await ctx.db.query("places").withIndex("by_slug",q=>q.eq("slug",args.slug)).first();if(slugExists)throw new Error("Slug already exists");const placeData={name:submission.name,slug:args.slug,city:args.city,country:args.country,neighborhood:args.neighborhood,address:submission.address,externalPlaceId:submission.googlePlaceId,priceLevel:2,status:"published" as const,createdAt:Date.now(),updatedAt:Date.now(),...(submission.latitude!==undefined?{latitude:submission.latitude}:{}),...(submission.longitude!==undefined?{longitude:submission.longitude}:{})};const placeId=await ctx.db.insert("places",placeData);await ctx.db.patch(submission._id,{status:"published",reviewedAt:Date.now(),updatedAt:Date.now()});return placeId}});
export const moderatePlaceSubmission=mutation({args:{adminToken:v.string(),submissionId:v.id("placeSubmissions"),status:v.union(v.literal("rejected"),v.literal("pending"))},handler:async(ctx,args)=>{authorize(args.adminToken);await ctx.db.patch(args.submissionId,{status:args.status,reviewedAt:Date.now(),updatedAt:Date.now()})}});
export const moderateUserRating=mutation({args:{adminToken:v.string(),ratingId:v.id("userRatings"),status:v.union(v.literal("approved"),v.literal("rejected"),v.literal("pending"))},handler:async(ctx,args)=>{authorize(args.adminToken);const rating=await ctx.db.get(args.ratingId);await ctx.db.patch(args.ratingId,{status:args.status,updatedAt:Date.now(),...(rating?{overallScore:overallFromRating(rating)}:{})})}});
export const repairOverallScores=mutation({args:{adminToken:v.string()},handler:async(ctx,args)=>{authorize(args.adminToken);let userRatings=0,dishRatings=0,automaticRatings=0;for(const rating of await ctx.db.query("userRatings").collect()){const overallScore=overallFromRating(rating);if(rating.overallScore!==overallScore){await ctx.db.patch(rating._id,{overallScore,updatedAt:Date.now()});userRatings++}}for(const rating of await ctx.db.query("dishRatings").collect()){if(rating.productType!=="bravas")continue;const overallScore=overallFromRating(rating);if(rating.overallScore!==overallScore){await ctx.db.patch(rating._id,{overallScore,updatedAt:Date.now()});dishRatings++}}for(const rating of await ctx.db.query("automaticRatings").collect()){const scores={...rating.scores};const overallScore=overallFromScores({potato:scores.potato??5,sauce:scores.sauce??5,spiciness:scores.spiciness??5,taste:scores.taste??5,texture:scores.texture??5,quantity:scores.quantity??5,value:scores.value??5});if(rating.overallScore!==overallScore||scores.overall!==overallScore){scores.overall=overallScore;await ctx.db.patch(rating._id,{overallScore,scores});automaticRatings++}}return{userRatings,dishRatings,automaticRatings}}});
