import { query } from "./_generated/server";
import { v } from "convex/values";

function confidence(score:number){return score>=72?"high":score>=42?"medium":"low"}
async function present(ctx:any,place:any){const rating=await ctx.db.query("dishRatings").withIndex("by_place",(q:any)=>q.eq("placeId",place._id)).filter((q:any)=>q.eq(q.field("productType"),"bravas")).first();if(!rating)return null;const userRatings=await ctx.db.query("userRatings").withIndex("by_place",(q:any)=>q.eq("placeId",place._id)).filter((q:any)=>q.eq(q.field("status"),"approved")).collect();const communityScore=userRatings.length?Math.round(userRatings.reduce((sum:number,row:any)=>sum+row.overallScore,0)/userRatings.length*10)/10:undefined;const communityPhotos=(await Promise.all(userRatings.filter((row:any)=>row.photoStorageId).map(async(row:any)=>({url:await ctx.storage.getUrl(row.photoStorageId),userName:row.userName,score:row.overallScore,comment:row.comment})))).filter((photo:any)=>photo.url);return{id:place._id,name:place.name,slug:place.slug,city:place.city,country:place.country,neighborhood:place.neighborhood,address:place.address,latitude:place.latitude,longitude:place.longitude,website:place.website,phone:place.phone,googlePlaceId:place.externalPlaceId,googleMapsUrl:place.googleMapsUrl,source:place.source,verifiedAt:place.verifiedAt,priceLevel:place.priceLevel,image:place.image,status:place.status,productType:rating.productType,scores:{overall:rating.overallScore,potato:rating.potatoScore,sauce:rating.sauceScore,spiciness:rating.spicinessScore,taste:rating.tasteScore,texture:rating.textureScore,quantity:rating.quantityScore,value:rating.valueScore},confidence:confidence(rating.confidenceScore),confidenceScore:rating.confidenceScore,evidenceCount:rating.evidenceCount,summary:{es:rating.summaryEs,en:rating.summaryEn},highlights:{es:rating.highlightsEs,en:rating.highlightsEn},methodologyVersion:rating.methodologyVersion,analyzedAt:new Date(rating.analyzedAt).toISOString().slice(0,10),communityScore,communityRatingCount:userRatings.length,communityPhotos}}

export const list=query({args:{},handler:async(ctx)=>{const places=await ctx.db.query("places").filter(q=>q.eq(q.field("status"),"published")).collect();const rows=await Promise.all(places.map(place=>present(ctx,place)));return rows.filter(Boolean)}});
export const bySlug=query({args:{slug:v.string()},handler:async(ctx,{slug})=>{const place=await ctx.db.query("places").withIndex("by_slug",q=>q.eq("slug",slug)).unique();return place?present(ctx,place):null}});
export const listBasic=query({args:{},handler:async(ctx)=>{const places=await ctx.db.query("places").filter(q=>q.eq(q.field("status"),"published")).collect();return places.map(place=>({id:place._id,name:place.name,neighborhood:place.neighborhood,city:place.city,status:place.status}))}});
export const findByExternalIds=query({args:{externalPlaceIds:v.array(v.string())},handler:async(ctx,{externalPlaceIds})=>{const rows=[];for(const externalPlaceId of externalPlaceIds.slice(0,20)){const place=await ctx.db.query("places").withIndex("by_external_place",q=>q.eq("externalPlaceId",externalPlaceId)).first();if(!place||place.status!=="published")continue;const rating=await ctx.db.query("dishRatings").withIndex("by_place",q=>q.eq("placeId",place._id)).filter(q=>q.eq(q.field("productType"),"bravas")).first();const community=await ctx.db.query("userRatings").withIndex("by_place",q=>q.eq("placeId",place._id)).filter(q=>q.eq(q.field("status"),"approved")).collect();const communityScore=community.length?Math.round(community.reduce((sum,row)=>sum+row.overallScore,0)/community.length*10)/10:null;rows.push({googlePlaceId:externalPlaceId,slug:place.slug,score:rating?.overallScore??communityScore,ratingCount:community.length})}return rows}});
