import { defineSchema,defineTable } from "convex/server";
import { v } from "convex/values";

const productType=v.union(v.literal("bravas"),v.literal("pimientos"),v.literal("tortilla"),v.literal("chipirones"),v.literal("pulpo"),v.literal("bocadillos"),v.literal("callos"),v.literal("croquetas"),v.literal("cachopo"),v.literal("chuleton"),v.literal("boquerones"),v.literal("calamares"),v.literal("cocido"),v.literal("paella"),v.literal("gazpacho"),v.literal("ensaladilla"),v.literal("ajoblanco"),v.literal("torreznos"),v.literal("montaditos"),v.literal("quesos"),v.literal("empanadas"));

export default defineSchema({
  placeImages:defineTable({placeId:v.id("places"),storageId:v.id("_storage"),createdBy:v.id("users"),updatedBy:v.id("users"),createdAt:v.number(),updatedAt:v.number()}).index("by_placeId",["placeId"]),
  restaurantScans:defineTable({key:v.string(),areaIndex:v.number(),searchOffset:v.number(),searchComplete:v.boolean(),finished:v.boolean(),checked:v.number(),imported:v.number(),reviewPages:v.number(),requests:v.number(),lease:v.optional(v.string()),leaseUntil:v.optional(v.number()),error:v.optional(v.string()),updatedAt:v.number()}).index("by_key",["key"]),
  restaurantScanTargets:defineTable({externalId:v.string(),dataId:v.string(),areaIndex:v.number(),status:v.union(v.literal("pending"),v.literal("complete")),nextPage:v.optional(v.string()),placeId:v.optional(v.id("places")),mentionCount:v.number(),evidenceCount:v.number(),reviewCount:v.optional(v.number()),limitReached:v.optional(v.boolean()),totals:v.record(v.string(),v.number()),weights:v.record(v.string(),v.number()),updatedAt:v.number()}).index("by_externalId",["externalId"]).index("by_areaIndex_and_status",["areaIndex","status"]),
  restaurantScanPages:defineTable({targetId:v.id("restaurantScanTargets"),page:v.string(),reviewCount:v.optional(v.number())}).index("by_targetId_and_page",["targetId","page"]),
  automaticRatings:defineTable({placeId:v.id("places"),overallScore:v.number(),scores:v.record(v.string(),v.number()),evidenceCount:v.number(),confidenceScore:v.number(),analyzedAt:v.number(),methodologyVersion:v.string(),complete:v.boolean()}).index("by_placeId",["placeId"]),
  users:defineTable({clerkUserId:v.string(),displayName:v.string(),email:v.optional(v.string()),imageUrl:v.optional(v.string()),createdAt:v.number(),updatedAt:v.number(),lastSeenAt:v.number()}).index("by_clerk_id",["clerkUserId"]).index("by_email",["email"]),
  places:defineTable({name:v.string(),slug:v.string(),city:v.string(),country:v.string(),neighborhood:v.string(),address:v.string(),latitude:v.optional(v.number()),longitude:v.optional(v.number()),externalPlaceId:v.optional(v.string()),googleMapsUrl:v.optional(v.string()),source:v.optional(v.union(v.literal("admin"),v.literal("google_places"))),createdBy:v.optional(v.string()),createdByUserRef:v.optional(v.id("users")),verifiedAt:v.optional(v.number()),website:v.optional(v.string()),phone:v.optional(v.string()),generalRating:v.optional(v.number()),generalReviewCount:v.optional(v.number()),priceLevel:v.number(),image:v.optional(v.string()),status:v.union(v.literal("draft"),v.literal("published"),v.literal("demo")),createdAt:v.number(),updatedAt:v.number()}).index("by_slug",["slug"]).index("by_city",["city"]).index("by_external_place",["externalPlaceId"]),
  dishRatings:defineTable({placeId:v.id("places"),productType,dishType:v.string(),overallScore:v.number(),potatoScore:v.number(),sauceScore:v.number(),spicinessScore:v.number(),tasteScore:v.number(),textureScore:v.number(),temperatureScore:v.optional(v.number()),quantityScore:v.number(),valueScore:v.number(),confidenceScore:v.number(),evidenceCount:v.number(),summaryEs:v.string(),summaryEn:v.string(),highlightsEs:v.array(v.string()),highlightsEn:v.array(v.string()),analyzedAt:v.number(),methodologyVersion:v.string(),createdAt:v.number(),updatedAt:v.number()}).index("by_place",["placeId"]).index("by_product_score",["productType","overallScore"]),
  reviewEvidence:defineTable({placeId:v.id("places"),productType,dishType:v.string(),source:v.string(),externalReviewId:v.optional(v.string()),sourceUrl:v.optional(v.string()),storedExcerpt:v.optional(v.string()),storagePermission:v.union(v.literal("allowed"),v.literal("derived_only"),v.literal("unknown")),attribute:v.string(),sentiment:v.union(v.literal("positive"),v.literal("neutral"),v.literal("negative")),score:v.number(),confidence:v.number(),analyzedAt:v.number(),modelVersion:v.string()}).index("by_place",["placeId"]).index("by_source",["source"]),
  reviewSources:defineTable({key:v.string(),name:v.string(),enabled:v.boolean(),supportsTextStorage:v.boolean(),termsUrl:v.optional(v.string()),updatedAt:v.number()}).index("by_key",["key"]),
  userRatings:defineTable({placeId:v.id("places"),productType,userId:v.string(),userRef:v.optional(v.id("users")),userName:v.string(),userImage:v.optional(v.string()),photoStorageId:v.optional(v.id("_storage")),overallScore:v.number(),potatoScore:v.number(),sauceScore:v.number(),spicinessScore:v.number(),tasteScore:v.number(),textureScore:v.number(),quantityScore:v.number(),valueScore:v.number(),comment:v.optional(v.string()),status:v.union(v.literal("pending"),v.literal("approved"),v.literal("rejected")),createdAt:v.number(),updatedAt:v.number()}).index("by_place",["placeId"]).index("by_place_user",["placeId","userId"]).index("by_user_updated",["userId","updatedAt"]).index("by_status",["status"]),
  placeSubmissions:defineTable({googlePlaceId:v.string(),name:v.string(),address:v.string(),latitude:v.optional(v.number()),longitude:v.optional(v.number()),googleMapsUrl:v.string(),submittedBy:v.string(),submittedByUserRef:v.optional(v.id("users")),submittedByName:v.string(),submittedByImage:v.optional(v.string()),status:v.union(v.literal("pending"),v.literal("published"),v.literal("rejected")),reviewedAt:v.optional(v.number()),createdAt:v.number(),updatedAt:v.number()}).index("by_google_place",["googlePlaceId"]).index("by_status",["status"]).index("by_user",["submittedBy"]),
});
