import type { Metadata } from "next";
import Link from "next/link";
import { PhotoViewer } from "@/components/PhotoViewer";
import { AdminPlaceImage } from "@/components/AdminPlaceImage";
import { notFound } from "next/navigation";
import { connection } from "next/server";
import { formatScore } from "@/lib/bravometro/scoring";
import { getPlaceBySlug,getPlaces } from "@/lib/data";
import { getDictionary,isLocale } from "@/lib/i18n";

export async function generateStaticParams(){const places=await getPlaces();return places.map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:{params:Promise<{locale:string;slug:string}>}):Promise<Metadata>{const{locale,slug}=await params;const place=await getPlaceBySlug(slug);return{title:place?`${place.name} · ${place.scores.overall.toFixed(1)}`:"Bravas",description:place?.summary[locale==="en"?"en":"es"],alternates:{canonical:`/${locale}/bravas/${slug}`,languages:{es:`/es/bravas/${slug}`,en:`/en/bravas/${slug}`}}}}

export default async function PlaceDetail({params}:{params:Promise<{locale:string;slug:string}>}){
  const{locale,slug}=await params;if(!isLocale(locale))notFound();await connection();const place=await getPlaceBySlug(slug);if(!place)notFound();const d=getDictionary(locale);
  const attributes=[["potato",d.attributes.potato],["sauce",d.attributes.sauce],["texture",d.attributes.texture],["taste",d.attributes.taste],["spiciness",d.attributes.spiciness],["quantity",d.attributes.quantity],["value",d.attributes.value],["presentation",d.attributes.presentation],["originality",d.attributes.originality]] as const;
  const structured={"@context":"https://schema.org","@type":"Restaurant",name:place.name,address:{"@type":"PostalAddress",streetAddress:place.address,addressLocality:place.city,addressCountry:place.country},servesCuisine:"Spanish",...(place.communityRatingCount?{aggregateRating:{"@type":"AggregateRating",ratingValue:place.communityScore,bestRating:10,ratingCount:place.communityRatingCount}}:place.automaticScore===undefined?{aggregateRating:{"@type":"AggregateRating",ratingValue:place.scores.overall,bestRating:10,ratingCount:place.evidenceCount}}:{})};
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured)}}/><section className="detail-hero"><div className="shell"><Link className="button ghost" href={`/${locale}/bravas`}>← {d.actions.back}</Link><div className="detail-top"><div><span className="eyebrow">{place.neighborhood} · {place.city}</span><h1 className="display" style={{fontSize:"clamp(3rem,7vw,5.8rem)"}}>{place.name}</h1><p className="lede">{place.summary[locale]}</p><div className="place-meta"><span className="pill">{place.status==="demo"?d.common.demo:"Bravómetro"}</span><span className="pill">v{place.methodologyVersion}</span><span className="pill">{place.evidenceCount} {d.common.evidence}</span></div></div><div className="card detail-score"><small style={{fontWeight:900}}>{d.common.score.toUpperCase()}</small><div className="big-score">{formatScore(place.scores.overall,locale)}</div><p style={{marginBottom:0}}>● {d.common.confidence}: <b>{d.common[place.confidence]} · {place.confidenceScore}%</b></p></div></div></div></section>
    <section className="section" style={{paddingTop:18}}><div className="shell">{place.image&&!place.communityPhotos?.length&&<PhotoViewer src={place.image} alt={place.name} locale={locale} hero/>}{process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY&&!place.communityRatingCount&&<AdminPlaceImage slug={place.slug} locale={locale} hasImage={Boolean(place.image)}/>} {place.automaticScore!==undefined&&<p>{locale==="es"?"Estimación IA provisional":"Provisional AI estimate"}: <b>{formatScore(place.automaticScore,locale)}</b> · {place.automaticEvidenceCount} {d.common.evidence}{!place.automaticComplete&&(locale==="es"?" · análisis parcial":" · partial analysis")}</p>}<h2 className="section-title" style={{fontSize:"clamp(1.8rem,4vw,3rem)",marginTop:38}}>{d.detail.breakdown}</h2><div className="score-grid">{attributes.map(([key,label])=><div className="card attribute" key={key}><div className="attribute-top"><span>{label}</span><b>{formatScore(place.scores[key],locale)}</b></div><div className="track"><div className="fill" style={{width:`${(place.scores[key]??0)*10}%`}}/></div></div>)}</div></div></section>
    <section className="section"><div className="shell content-grid"><article className="card content-card"><h2>{d.detail.summary}</h2><p>{place.summary[locale]}</p><h2 style={{marginTop:28}}>{d.detail.evidenceTitle}</h2><p>{d.detail.evidencePending}</p>{place.communityRatingCount?<div className="community-score"><strong>{formatScore(place.communityScore??0,locale)}</strong><span>{d.contribute.communityScore}<small>{place.communityRatingCount} {d.common.evidence}</small></span></div>:null}<Link className="button" href={`/${locale}/publicar`}>＋ {d.contribute.ratePlace}</Link></article><aside className="card content-card"><h2>{d.detail.highlights}</h2><ul className="highlight-list">{place.highlights[locale].map(h=><li key={h}>✓ {h}</li>)}</ul><h2 style={{marginTop:28}}>{d.detail.address}</h2><p>{place.address}</p>{(place.googleMapsUrl||place.googlePlaceId)&&<a className="button secondary" href={place.googleMapsUrl||`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(place.name)}&query_place_id=${encodeURIComponent(place.googlePlaceId!)}`} target="_blank" rel="noreferrer">Google Maps ↗</a>}<p><b>{d.detail.analyzed}:</b> {new Intl.DateTimeFormat(locale).format(new Date(place.analyzedAt))}</p><Link className="button secondary" href={`/${locale}/metodologia`}>{d.detail.methodology} →</Link></aside></div></section>
    {place.communityPhotos?.length?<section className="section" style={{paddingTop:0}}><div className="shell"><h2 className="section-title" style={{fontSize:"clamp(1.8rem,4vw,3rem)"}}>{d.detail.communityPhotos}</h2><div className="community-photo-grid">{place.communityPhotos.map((photo,index)=><article className="card community-photo-card" key={`${photo.url}-${index}`}><PhotoViewer src={photo.url} alt={`${d.contribute.photo}: ${place.name}`} locale={locale}/><div><b>{photo.userName} · {formatScore(photo.score,locale)}</b>{photo.comment&&<p>“{photo.comment}”</p>}</div></article>)}</div></div></section>:null}
  </>;
}
