"use client";
import { useState } from "react";
import type { Dictionary } from "@/lib/i18n";
import type { Place } from "@/lib/types";

type PendingPlace={_id:string;name:string;address:string;submittedByName:string};
type PendingRating={_id:string;userName:string;placeName:string;overallScore:number;comment?:string;photoUrl?:string};

export function AdminPanel({places,dictionary:d,enabled}:{places:Place[];dictionary:Dictionary;enabled:boolean}){
  const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);const[queue,setQueue]=useState<{places:PendingPlace[];ratings:PendingRating[]}|null>(null);
  async function post(body:Record<string,unknown>){const response=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error);return data}
  async function submit(form:HTMLFormElement){setBusy(true);setMessage("");try{await post(Object.fromEntries(new FormData(form)));setMessage("✓ Guardado correctamente");form.reset()}catch(error){setMessage(`Error: ${error instanceof Error?error.message:"Conexión"}`)}finally{setBusy(false)}}
  async function loadQueue(){setBusy(true);try{const response=await fetch("/api/admin",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error);setQueue(data)}catch(error){setMessage(`Error: ${error instanceof Error?error.message:"Conexión"}`)}finally{setBusy(false)}}
  async function moderate(body:Record<string,unknown>){setBusy(true);try{await post(body);setMessage("✓ Moderación guardada");await loadQueue()}catch(error){setMessage(`Error: ${error instanceof Error?error.message:"Conexión"}`);setBusy(false)}}
  async function repairScores(){setBusy(true);setMessage("");try{const data=await post({operation:"repairOverallScores"});setMessage(`✓ Medias reparadas: ${JSON.stringify(data.result)}`)}catch(error){setMessage(`Error: ${error instanceof Error?error.message:"Conexión"}`)}finally{setBusy(false)}}
  function approvePlace(item:PendingPlace){const suggested=item.name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");const slug=prompt("Slug",suggested);const city=slug&&prompt("Ciudad","Madrid");const neighborhood=city&&prompt("Barrio","");if(slug&&city&&neighborhood)void moderate({operation:"approvePlaceSubmission",submissionId:item._id,slug,city,neighborhood,country:"ES"})}
  return <>
    <div className="card form-card" style={{margin:"24px 0"}}>{!enabled&&<p className="notice" style={{marginBottom:0}}>{d.admin.setup}</p>}{message&&<p className="notice" style={{marginBottom:0}}>{message}</p>}</div>
    <section className="card content-card" style={{marginBottom:18}}><h2>Aportaciones pendientes</h2><button className="button secondary" disabled={!enabled||busy} onClick={()=>void loadQueue()}>Cargar cola</button><button className="button secondary" style={{marginLeft:10}} disabled={!enabled||busy} onClick={()=>void repairScores()}>Rehacer notas medias</button>{queue&&<div className="moderation-list"><h3>Sitios ({queue.places.length})</h3>{queue.places.map(item=><div className="moderation-row" key={item._id}><span><b>{item.name}</b><small>{item.address} · {item.submittedByName}</small></span><div><button className="button secondary" onClick={()=>approvePlace(item)}>Aprobar</button><button className="button ghost" onClick={()=>void moderate({operation:"rejectPlaceSubmission",submissionId:item._id})}>Rechazar</button></div></div>)}<h3>Valoraciones ({queue.ratings.length})</h3>{queue.ratings.map(item=><div className="moderation-row rating-moderation-row" key={item._id}>{item.photoUrl&&<div className="moderation-photo" role="img" aria-label={`Foto de ${item.placeName}`} style={{backgroundImage:`url(${item.photoUrl})`}}/>}<span><b>{item.placeName} · {item.userName} · {item.overallScore}/10</b><small>{item.comment||"Sin comentario"}</small></span><div><button className="button secondary" onClick={()=>void moderate({operation:"approveUserRating",ratingId:item._id})}>Aprobar</button><button className="button ghost" onClick={()=>void moderate({operation:"rejectUserRating",ratingId:item._id})}>Rechazar</button></div></div>)}</div>}</section>
    <div className="admin-grid"><form className="card form-card form-grid" onSubmit={e=>{e.preventDefault();void submit(e.currentTarget)}}><input type="hidden" name="operation" value="upsertPlace"/><h2 className="field full">{d.admin.save}</h2><div className="field"><label>{d.admin.name}</label><input className="input" name="name" required/></div><div className="field"><label>{d.admin.slug}</label><input className="input" name="slug" required pattern="[a-z0-9-]+"/></div><div className="field"><label>{d.common.city}</label><input className="input" name="city" defaultValue="Madrid" required/></div><div className="field"><label>{d.common.neighborhood}</label><input className="input" name="neighborhood" required/></div><div className="field full"><label>Dirección</label><input className="input" name="address" required/></div><button className="button field full" disabled={!enabled||busy}>{busy?d.common.loading:d.admin.save}</button></form>
    <form className="card form-card form-grid" onSubmit={e=>{e.preventDefault();void submit(e.currentTarget)}}><input type="hidden" name="operation" value="upsertRating"/><h2 className="field full">{d.admin.rating}</h2><div className="field full"><label>Establecimiento</label><select className="select" name="placeSlug" required><option value="">—</option>{places.map(p=><option key={p.id} value={p.slug}>{p.name}</option>)}</select></div>{["potato","sauce","spiciness","taste","texture","quantity","value"].map(key=><div className="field" key={key}><label>{key}</label><input className="input" name={key} type="number" min="0" max="10" step="0.1" required/></div>)}<div className="field"><label>Evidencias</label><input className="input" name="evidenceCount" type="number" min="0" required/></div><div className="field full"><label>Resumen ES</label><textarea className="textarea" name="summaryEs" required/></div><div className="field full"><label>Summary EN</label><textarea className="textarea" name="summaryEn" required/></div><button className="button field full" disabled={!enabled||busy}>{busy?d.common.loading:d.admin.save}</button></form></div>
    <div className="card content-card" style={{marginTop:18}}><h2>{d.nav.places}</h2>{places.map(p=><div className="moderation-row" key={p.id}><span><b>{p.name}</b><small>{p.slug} · {p.status}</small></span><span><button className="button secondary" disabled={!enabled||p.status==="demo"} onClick={()=>void moderate({operation:"deleteRating",placeSlug:p.slug})}>{d.admin.delete} rating</button><button className="button secondary" disabled={!enabled||p.status==="demo"} onClick={()=>void moderate({operation:"deletePlace",placeId:p.id})}>{d.admin.delete}</button></span></div>)}</div>
  </>;
}
