"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import { Show,SignInButton } from "@clerk/nextjs";
import { GooglePlacesMap } from "@/components/GooglePlacesMap";
import type { Dictionary } from "@/lib/i18n";
import { prepareRatingPhoto } from "@/lib/rating-photo";
import type { GooglePlaceCandidate,Locale } from "@/lib/types";

const scoreKeys=["potato","sauce","spiciness","taste","texture","quantity","value"] as const;

export function ContributePanel({locale,dictionary:d,authEnabled,searchEnabled,storageEnabled,mapApiKey,mapId,initialPlaceId}:{locale:Locale;dictionary:Dictionary;authEnabled:boolean;searchEnabled:boolean;storageEnabled:boolean;mapApiKey?:string;mapId?:string;initialPlaceId?:string}){
  if(!authEnabled)return <div className="card content-card"><h2>{d.contribute.signIn}</h2><p>{d.contribute.setup}</p></div>;
  return <><Show when="signed-out"><div className="card content-card sign-in-card"><span className="meter-emoji">🔐</span><h2>{d.contribute.signIn}</h2><p>{locale==="es"?"Sin contraseñas nuevas: usa Google, Apple, Facebook o X si están activados en Clerk. En Android, la opción recomendada es Google.":"No new password: use Google, Apple, Facebook or X when enabled in Clerk. On Android, Google is the recommended option."}</p><div className="provider-pills" aria-label={locale==="es"?"Proveedores compatibles":"Supported providers"}><span>G Google</span><span>● Apple</span><span>f Facebook</span><span>𝕏</span></div><SignInButton mode="modal"><button className="button">{d.contribute.signIn} →</button></SignInButton></div></Show><Show when="signed-in"><RatingFlow locale={locale} d={d} searchEnabled={searchEnabled} storageEnabled={storageEnabled} mapApiKey={mapApiKey} mapId={mapId} initialPlaceId={initialPlaceId}/></Show></>;
}

function RatingFlow({locale,d,searchEnabled,storageEnabled,mapApiKey,mapId,initialPlaceId}:{locale:Locale;d:Dictionary;searchEnabled:boolean;storageEnabled:boolean;mapApiKey?:string;mapId?:string;initialPlaceId?:string}){
  const[query,setQuery]=useState("");const[results,setResults]=useState<GooglePlaceCandidate[]>([]);const[selected,setSelected]=useState<GooglePlaceCandidate|null>(null);const[userLocation,setUserLocation]=useState<{latitude:number;longitude:number}|null>(null);const[loading,setLoading]=useState(false);const[locating,setLocating]=useState(false);const[message,setMessage]=useState("");const[formVersion,setFormVersion]=useState(0);const[photo,setPhoto]=useState<File|null>(null);const[photoPreview,setPhotoPreview]=useState<string>();const[photoProcessing,setPhotoProcessing]=useState(false);
  const initialLoaded=useRef(false);
  useEffect(()=>()=>{if(photoPreview)URL.revokeObjectURL(photoPreview)},[photoPreview]);
  useEffect(()=>{if(!initialPlaceId||!searchEnabled||initialLoaded.current)return;initialLoaded.current=true;setLoading(true);void fetch("/api/places/details",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({googlePlaceId:initialPlaceId,locale})}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);setResults([data.place]);setSelected(data.place)}).catch(error=>setMessage(error instanceof Error?error.message:"Error")).finally(()=>setLoading(false))},[initialPlaceId,locale,searchEnabled]);
  const selectPlace=useCallback((googlePlaceId:string)=>{setSelected(results.find(place=>place.googlePlaceId===googlePlaceId)??null);setMessage("")},[results]);
  async function requestPlaces(endpoint:string,body:Record<string,unknown>){setLoading(true);setMessage("");try{const response=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,locale})});const data=await response.json();if(!response.ok)throw new Error(data.error);const next=data.places??[];setResults(next);setSelected(null);if(!next.length)setMessage(d.contribute.noPlaces)}catch(error){setMessage(error instanceof Error?error.message:"Error")}finally{setLoading(false)}}
  async function search(){if(query.trim().length<3)return;await requestPlaces("/api/places/search",{query})}
  function nearby(){if(!navigator.geolocation){setMessage(d.contribute.locationUnsupported);return}setLocating(true);setMessage("");navigator.geolocation.getCurrentPosition(position=>{const location={latitude:position.coords.latitude,longitude:position.coords.longitude};setUserLocation(location);setLocating(false);void requestPlaces("/api/places/nearby",location)},()=>{setLocating(false);setMessage(d.contribute.locationError)},{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
  async function choosePhoto(file?:File){if(!file)return;setPhotoProcessing(true);setMessage(d.contribute.processingPhoto);try{const prepared=await prepareRatingPhoto(file);setPhoto(prepared);setPhotoPreview(previous=>{if(previous)URL.revokeObjectURL(previous);return URL.createObjectURL(prepared)});setMessage("")}catch(error){setPhoto(null);setPhotoPreview(undefined);setMessage(error instanceof Error?error.message:"Error")}finally{setPhotoProcessing(false)}}
  function removePhoto(){setPhoto(null);setPhotoPreview(previous=>{if(previous)URL.revokeObjectURL(previous);return undefined})}
  async function uploadPhoto(){if(!photo)return undefined;setMessage(d.contribute.uploadingPhoto);const prepareResponse=await fetch("/api/uploads/rating-photo",{method:"POST"});const prepareData=await prepareResponse.json();if(!prepareResponse.ok)throw new Error(prepareData.error);const uploadResponse=await fetch(prepareData.uploadUrl,{method:"POST",headers:{"Content-Type":photo.type},body:photo});const uploadData=await uploadResponse.json();if(!uploadResponse.ok||!uploadData.storageId)throw new Error(d.contribute.photoError);return String(uploadData.storageId)}
  async function submitRating(form:HTMLFormElement){if(!selected)return;setLoading(true);setMessage("");const values=Object.fromEntries(new FormData(form));try{const photoStorageId=await uploadPhoto();const response=await fetch("/api/contributions/rating",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...values,googlePlaceId:selected.googlePlaceId,locale,...(photoStorageId?{photoStorageId}:{})})});const data=await response.json();if(!response.ok)throw new Error(data.error);removePhoto();setMessage(d.contribute.ratingPending);setFormVersion(value=>value+1)}catch(error){setMessage(error instanceof Error?error.message:"Error")}finally{setLoading(false)}}
  return <div className="rating-flow">
    <section className="card place-picker-card"><div className="place-picker-head"><div><span className="eyebrow">Google Places</span><h2>{d.contribute.findPlace}</h2><p>{d.contribute.searchHelp}</p></div><button className="button secondary location-button" type="button" onClick={nearby} disabled={!searchEnabled||locating||loading}>⌖ {locating?d.contribute.locating:d.contribute.nearMe}</button></div>{!searchEnabled&&<div className="notice">{d.contribute.setup}</div>}
      <div className="place-search"><label htmlFor="google-place-query">{d.contribute.searchLabel}</label><div className="place-search-row"><input id="google-place-query" className="input" value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();void search()}}} placeholder={d.contribute.searchPlaceholder} disabled={!searchEnabled}/><button className="button" type="button" onClick={()=>void search()} disabled={!searchEnabled||loading}>{loading?"…":d.actions.search}</button></div></div>
      {userLocation&&<p className="location-privacy">● {d.contribute.locationReady}</p>}
      <GooglePlacesMap apiKey={mapApiKey} mapId={mapId} places={results} selectedId={selected?.googlePlaceId} userLocation={userLocation} onSelect={selectPlace} unavailableLabel={d.contribute.mapSetup}/>
      {results.length>0&&<div className="results-count">{results.length} {d.contribute.results}</div>}
      <div className="google-results" role="list">{results.map(place=><button type="button" role="listitem" className={`google-result ${selected?.googlePlaceId===place.googlePlaceId?"selected":""}`} key={place.googlePlaceId} onClick={()=>selectPlace(place.googlePlaceId)}><span className="google-mark">G</span><span><b>{place.name}</b><small>{place.address}</small></span><span>›</span></button>)}</div>
    </section>
    <form key={formVersion} className="card contribution-card rating-card" onSubmit={event=>{event.preventDefault();void submitRating(event.currentTarget)}}><span className="eyebrow">Bravómetro</span><h2>{d.contribute.ratePlace}</h2>{selected?<div className="selected-place compact"><span className="pill">✓ Google Place</span><h3>{selected.name}</h3><p>{selected.address}</p><a href={selected.googleMapsUrl} target="_blank" rel="noreferrer">{locale==="es"?"Ver en Google Maps":"View on Google Maps"} ↗</a></div>:<div className="rating-empty">⌖<b>{d.contribute.selectPlace}</b><span>{d.contribute.selectPlaceHelp}</span></div>}{!storageEnabled&&<div className="notice">{d.contribute.setup}</div>}<fieldset disabled={!selected||!storageEnabled||loading||photoProcessing}><div className="rating-sliders">{scoreKeys.map(key=><ScoreInput key={key} name={key} label={d.attributes[key]}/>)}</div><div className="field"><label htmlFor="rating-comment">{d.contribute.comment}</label><textarea id="rating-comment" className="textarea" name="comment" maxLength={600}/></div><div className="field rating-photo-field"><label htmlFor="rating-photo">{d.contribute.photo}</label><p>{d.contribute.photoHelp}</p>{photoPreview?<div className="rating-photo-preview" role="img" aria-label={d.contribute.photoPreview} style={{backgroundImage:`url(${photoPreview})`}}><button type="button" onClick={removePhoto} aria-label={d.contribute.removePhoto}>×</button></div>:<label className="rating-photo-picker" htmlFor="rating-photo"><span>＋</span><b>{photoProcessing?d.contribute.processingPhoto:d.contribute.addPhoto}</b><small>{d.contribute.photoFormats}</small></label>}<input id="rating-photo" className="visually-hidden" type="file" accept=".heic,.heif,image/heic,image/heif,image/heic-sequence,image/heif-sequence,image/jpeg,image/png,image/webp" onChange={event=>void choosePhoto(event.target.files?.[0])}/></div><button className="button rating-submit">{loading||photoProcessing?d.common.loading:d.contribute.submitRating}</button></fieldset>
    </form>{message&&<div className="notice contribution-message">{message}</div>}
  </div>;
}

function ScoreInput({name,label}:{name:string;label:string}){const[value,setValue]=useState(5);return <div className="score-input"><label htmlFor={`score-${name}`}>{label}<output>{value.toFixed(1)}</output></label><input id={`score-${name}`} name={name} type="range" min="0" max="10" step="0.5" value={value} onChange={event=>setValue(Number(event.target.value))}/></div>}
