"use client";
import { useCallback,useState } from "react";
import Link from "next/link";
import { GooglePlacesMap } from "@/components/GooglePlacesMap";
import { formatScore } from "@/lib/bravometro/scoring";
import type { Dictionary } from "@/lib/i18n";
import type { GooglePlaceSearchResult,Locale } from "@/lib/types";

export function HomePlaceSearch({locale,dictionary:d,enabled,mapApiKey,mapId}:{locale:Locale;dictionary:Dictionary;enabled:boolean;mapApiKey?:string;mapId?:string}){
  const[query,setQuery]=useState("");const[results,setResults]=useState<GooglePlaceSearchResult[]>([]);const[selectedId,setSelectedId]=useState<string>();const[userLocation,setUserLocation]=useState<{latitude:number;longitude:number}|null>(null);const[loading,setLoading]=useState(false);const[locating,setLocating]=useState(false);const[message,setMessage]=useState("");
  const selectPlace=useCallback((googlePlaceId:string)=>setSelectedId(googlePlaceId),[]);
  async function load(endpoint:string,body:Record<string,unknown>){setLoading(true);setMessage("");try{const response=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,locale})});const data=await response.json();if(!response.ok)throw new Error(data.error);const places:GooglePlaceSearchResult[]=data.places??[];setResults(places);setSelectedId(places[0]?.googlePlaceId);if(!places.length)setMessage(d.contribute.noPlaces)}catch(error){setMessage(error instanceof Error?error.message:"Error")}finally{setLoading(false)}}
  function search(){if(query.trim().length>=3)void load("/api/places/search",{query})}
  function nearby(){if(!navigator.geolocation){setMessage(d.contribute.locationUnsupported);return}setLocating(true);setMessage("");navigator.geolocation.getCurrentPosition(position=>{const location={latitude:position.coords.latitude,longitude:position.coords.longitude};setUserLocation(location);setLocating(false);void load("/api/places/nearby",location)},()=>{setLocating(false);setMessage(d.contribute.locationError)},{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
  return <div className="home-place-finder"><div className="hero-search"><input value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();search()}}} aria-label={d.actions.search} placeholder={d.hero.search} disabled={!enabled}/><button className="button" type="button" onClick={search} disabled={!enabled||loading||query.trim().length<3}>{loading?"…":`${d.actions.search} →`}</button></div><button className="home-nearby" type="button" onClick={nearby} disabled={!enabled||locating||loading}>⌖ {locating?d.contribute.locating:d.contribute.nearMe}</button>{message&&<div className="notice home-search-message">{message}</div>}
    {results.length>0&&<div className="card home-search-results"><div className="home-search-map"><GooglePlacesMap apiKey={mapApiKey} mapId={mapId} places={results} selectedId={selectedId} userLocation={userLocation} onSelect={selectPlace} unavailableLabel={d.contribute.mapSetup}/></div><div className="home-result-list">{results.map(place=>{const rated=place.local?.score!==null&&place.local?.score!==undefined;return <article className={`home-result ${selectedId===place.googlePlaceId?"selected":""}`} key={place.googlePlaceId}><button type="button" onClick={()=>setSelectedId(place.googlePlaceId)}><span className="google-mark">G</span><span><b>{place.name}</b><small>{place.address}</small></span></button><div className="home-result-status">{rated?<strong>{formatScore(place.local!.score!,locale)}</strong>:<span className="pill">{d.common.notRated}</span>}<span className="home-result-actions">{rated&&<Link className="button ghost" href={`/${locale}/bravas/${place.local!.slug}`}>{d.actions.viewPlace}</Link>}<Link className="button" href={`/${locale}/publicar?place=${encodeURIComponent(place.googlePlaceId)}`}>{d.contribute.ratePlace}</Link></span></div></article>})}</div></div>}
  </div>;
}
