import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { HomePlaceSearch } from "@/components/HomePlaceSearch";
import { PlaceCard } from "@/components/PlaceCard";
import { getPlaces } from "@/lib/data";
import { getDictionary, isLocale } from "@/lib/i18n";
import { futureMeters } from "@/lib/meters";

export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const {locale}=await params;return {title:locale==="en"?"Find the best patatas bravas":"Descubre las mejores patatas bravas",alternates:{canonical:`/${locale}`,languages:{es:"/es",en:"/en"}}}}

export default async function Home({params}:{params:Promise<{locale:string}>}){
  const {locale}=await params;if(!isLocale(locale))notFound();const d=getDictionary(locale);const places=(await getPlaces()).filter(p=>p.productType==="bravas").sort((a,b)=>b.scores.overall-a.scores.overall);
  return <>
    <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><span className="eyebrow">{d.hero.eyebrow}</span><h1 className="display">{d.hero.title}<span className="accent">{d.hero.accent}</span></h1><p className="lede">{d.hero.description}</p>
      <HomePlaceSearch locale={locale} dictionary={d} enabled={Boolean(process.env.GOOGLE_MAPS_API_KEY)} mapApiKey={process.env.NEXT_PUBLIC_GOOGLE_MAPS_BROWSER_KEY} mapId={process.env.NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID}/><p className="hero-note">● {d.hero.popular}</p><div className="hero-actions"><Link className="button" href={`/${locale}/ranking`}>{d.actions.viewRanking}</Link><Link className="button secondary" href={`/${locale}/metodologia`}>{d.nav.methodology}</Link></div></div>
      <div className="hero-visual" aria-hidden="true"><div className="hero-blob"/><Image className="hero-mascot" src="/assets/mascot.png" width={1254} height={1254} alt="" priority/><div className="card score-float"><span style={{fontSize:12,fontWeight:900}}>BRAVÓMETRO</span><strong>8,7</strong><small>{d.common.high} · 84%</small></div></div>
    </div></section>
    <section className="section"><div className="shell"><div className="section-head" style={{marginTop:34}}><div><span className="eyebrow">Top Bravómetro</span><h2 className="section-title">{d.ranking.title}</h2><p className="lede">{d.ranking.description}</p></div><Link className="button secondary" href={`/${locale}/ranking`}>{d.actions.viewRanking} →</Link></div>{places.length?<div className="grid-3">{places.slice(0,3).map((place,index)=><PlaceCard key={place.id} place={place} locale={locale} dictionary={d} rank={index+1}/>)}</div>:<div className="card content-card empty-ranking"><h3>{locale==="es"?"El ranking aún está calentando":"The ranking is warming up"}</h3><p>{locale==="es"?"Busca un establecimiento arriba y sé la primera persona en valorar sus bravas.":"Find a venue above and be the first to rate its bravas."}</p><Link className="button" href={`/${locale}/publicar`}>{d.contribute.ratePlace} →</Link></div>}</div></section>
    <section className="section" style={{background:"#fff3d5"}}><div className="shell"><div className="section-head"><div><span className="eyebrow">{d.methodology.eyebrow}</span><h2 className="section-title">{d.methodology.title}</h2><p className="lede">{d.methodology.description}</p></div><Link className="button" href={`/${locale}/metodologia`}>{d.nav.methodology} →</Link></div><div className="method-grid"><div className="card method-card"><span className="method-number">1</span><h3>{locale==="es"?"Recogemos señales":"We collect signals"}</h3><p>{locale==="es"?"Separamos fuente, evidencia permitida y datos derivados.":"We separate sources, permitted evidence and derived data."}</p></div><div className="card method-card"><span className="method-number">2</span><h3>{locale==="es"?"Entendemos atributos":"We understand attributes"}</h3><p>{locale==="es"?"Patata, salsa, picante, sabor, textura, cantidad y valor.":"Potato, sauce, heat, taste, texture, quantity and value."}</p></div><div className="card method-card"><span className="method-number">3</span><h3>{locale==="es"?"Explicamos el resultado":"We explain the result"}</h3><p>{locale==="es"?"Una nota con confianza, volumen y versión metodológica.":"A score with confidence, volume and methodology version."}</p></div></div></div></section>
    <section className="section"><div className="shell"><div className="section-head"><div><span className="eyebrow">{d.meters.eyebrow}</span><h2 className="section-title">{d.meters.title}</h2><p className="lede">{d.meters.description} {d.meters.primary}</p></div><Link className="button secondary" href={`/${locale}/metros`}>{d.footer.discover} →</Link></div><div className="meter-grid">{futureMeters.slice(0,4).map(m=><Link className="card meter-card" key={m.slug} href={`/${locale}/metros/${m.slug}`}><span className="meter-emoji">{m.emoji}</span><h3>{m.name[locale]}</h3><p>{m.description[locale]}</p><span className="pill">{d.meters.kitchen}</span></Link>)}</div></div></section>
  </>;
}
